name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Обновлено с v2 до v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Обновлено с v2 до v3
        with:
          node-version: '20'  # Используйте актуальную версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3  # Эта версия также поддерживает Node 20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Путь к папке с вашими собранными файлами
